name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ${{ matrix.target }}
    strategy:
      matrix:
        target: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: WinSdk
        uses: fbactions/setup-winsdk@v1
        with:
          winsdk-build-version: 19041
      - run: Get-ItemProperty -Path "HKLM:\\Software\\Microsoft\\Windows Kits\\Installed Roots"
      #- name: Get path
      #  run: tree "C:\\Program Files (x86)\\Microsoft SDKs\\Windows Kits" /F
      - name: Get All
        run: tree "C:\\Program Files (x86)\\Microsoft SDKs\\Windows" /F
      - name: Get Others
        run: tree "C:\\Program Files (x86)\\Windows Kits\\10" /F
            #- name: Setup zig
            #uses: goto-bus-stop/setup-zig@v2
            #with: 
            #version: master
          #- name: Build
          #run: zig build
