name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ${{ matrix.target }}
    strategy:
      matrix:
        target: [fedora-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
        with: 
          version: master
      - name: Build
        run: zig build
